### ISSUE TITLE
Install script not working on Windows/msys and mac

### ISSUE THREAD

**Issue by wilsonk** [EmmaTheMartian/clockwork#1]
We have an open issue in Lilly for this (https://github.com/tauraamui/lilly/issues/267). It seems like the scripts/symlink.vsh script isn't quite set up for msys/mac.

Just making an issue here to link to the original, and to discuss any possible solutions.

**Comment by EmmaTheMartian** [comment]
I see why it does not work on Windows, the symlink.vsh script is based on the `v symlink` on *nix systems. Although I am not quite sure why it does not work on mac. I do not have a mac nor windows device to test on, but I can try to adapt the vsymlink scripts again and see if I can get something working.

**Comment by EmmaTheMartian** [comment]
Alright, could you take a look at the [fix/symlink](https://github.com/EmmaTheMartian/clockwork/tree/fix/symlink) branch and see if it works?

**Comment by wilsonk** [comment]
I tried the new branch and it almost works on msys/windows...the only issue is that the symlink from ```~/.local/share/clockwork/build/.bin/clockwork``` links to ``` ~/.local/share/clockwork/build/clockwork```, but the binary on windows ends up being called ```clockwork.exe``` when built. So the either the binary needs to be renamed to just 'clockwork' (which is what I did) or the symlink needs to point specifically to 'clockwork.exe' on msys/windows, I believe.

Works on mac! :)

**Comment by EmmaTheMartian** [comment]
Oh okay! I should be able to get that fixed now

**Comment by EmmaTheMartian** [comment]
Just pushed a new commit which should fix it, if you don't mind giving it another try that would be awesome.

**Comment by wilsonk** [comment]
Yep, that seems to have worked :)
